### ISSUE TITLE
chrome-extension://ljdojpkkdahpkbcceoogenoniodldfcna/build/index.html

### ISSUE THREAD

**Issue by kookfeng** [duan602728596/48tools#1]
运行exe后弹出标题为chrome-extension://ljdojpkkdahpkbcceoogenoniodldfcna/build/index.html的窗口
内容为：

找不到您的文件

该文件可能已被移至别处或遭到删除。
ERR_FILE_NOT_FOUND

————

将app.nw用nw.exe打开后提示
无法加载以下来源的扩展程序，清单文件缺失或不可读

**Comment by duan602728596** [comment]
你编译源文件了吗？
