### ISSUE TITLE
"Missing File Error - Unable to find locale data files. Please reinstall."

### ISSUE THREAD

**Issue by sheronimo** [duan602728596/48tools#10]
下载48tools(v2.1.0 x64)从releases. 在运行之前, 下载nodejs的最新版本和nw(通过npm). 试着运行`nw.exe`和`48tools(x64).exe`但我收到了"Missing file error - Unable to find locale data files. Please reinstall."尝试更改系统区域设置, 出现相同的错误. dbq我的技术知识有限
![image](https://user-images.githubusercontent.com/17737603/59208961-75f79c00-8bd4-11e9-8404-ef18575968dd.png)

**Comment by duan602728596** [comment]
等我明天用单位的windows看看的




| |
段昊辰
邮箱：duanhaochen@126.com
|

签名由 网易邮箱大师 定制

On 06/11/2019 00:08, sheronimo wrote:

下载48tools(v2.1.0 x64)从releases. 在运行之前, 下载nodejs的最新版本和nw(通过npm). 试着运行nw.exe和48tools(x64).exe但我收到了"Missing file error - Unable to find locale data files. Please reinstall."尝试更改系统区域设置, 出现相同的错误. dbq我的技术知识有限

**Comment by duan602728596** [comment]
你试一试关闭所有杀毒软件，然后重新解压缩。

**Comment by sheronimo** [comment]
感谢你的帮助,可以运行program. 杀毒软件已删除`.pak`. ^-^b

**Comment by duan602728596** [comment]
这种就是杀毒软件误删了
