### ISSUE TITLE
直播正常，直播回放卻一直轉圈

### ISSUE THREAD

**Issue by pande4848448** [duan602728596/48tools#101]
## 错误报告

都有配置正常配置ffmpeg，但在看直播回放的時候都會無限轉圈
![未命名](https://github.com/duan602728596/48tools/assets/154867784/eff09c25-14f8-4837-92a8-8040802315fd)

## 预期行为

流暢的觀看回放

## 使用环境

- 操作系统：windows
- 软件版本：4.7.0

**Comment by duan602728596** [comment]
测试能够正常的看录播。转圈要看网速是否有问题。配置完ffmpeg后要重新启动才能生效。
