### ISSUE TITLE
请教一下4.50和4.70版本区别，48tools下载直播和M3U8下载直播的区别？

### ISSUE THREAD

**Issue by heartFire9** [duan602728596/48tools#102]
## 错误报告

48tools 4.5.0不能下载直播
![634fd50d80854b134c21de54fbb821fc](https://github.com/duan602728596/48tools/assets/37868129/eb679ed8-5489-426c-b402-0d26146d069c)
![11fe9341b6921af8165bab0ff0507f3e](https://github.com/duan602728596/48tools/assets/37868129/317ba475-a789-4a8a-a54a-e0e08070b7a7)

M3U8Dwonloader2.1下载口袋直播会存在 少录最后一小段视频的BUG
![image](https://github.com/duan602728596/48tools/assets/37868129/719b224e-4b11-4ae3-bbfc-e127bedf20e7)

## 复现步骤

1从20231224开始，出现48tools 4.5.0不能下载口袋直播的问题。

2我这几天临时使用了M3U8Dwonloader2.1下载，（M3U8Dwonloader2.1下载口袋直播会存在 少录最后一小段视频的BUG）。

3升级到48tools4.7.0版本以后，功能恢复正常。

## 使用环境
- 操作系统：WIN11 22H2 
- ffmpeg version 6.0-full_build
- 软件版本：48tools 4.5.0&4.7.0  和 M3U8Dwonloader2.1下载

**Comment by duan602728596** [comment]
标题有非法字符，存得时候换个文件名。window的路径问题。
M3U8Dwonloader没用过，我也不清楚。
