### ISSUE TITLE
新人ID及时长

### ISSUE THREAD

**Issue by yunyeshanzhu** [duan602728596/48tools#103]
一：刚出道的新人焦玥 的直播ID是不是没更新到  我找了一下没找到

二：关于时长 目前视频点开可以直接看到1个小时内的时长 但超过1个小时的就需要自己拉进度条  可不可以将所有时长的具体时间都直接显示出来

**Comment by duan602728596** [comment]
新人ID已经更新。时长问题是UI问题，原生播放器就是这样的，我没法修改。
