### ISSUE TITLE
希望可以录制超清公演直播

### ISSUE THREAD

**Issue by mskgroup** [duan602728596/48tools#107]
希望可以登录账号后录制超清公演直播

**Comment by duan602728596** [comment]
现在不确定超清的直播地址和是否验证vip。

**Comment by mskgroup** [comment]
> 现在不确定超清的直播地址和是否验证vip。

如果需要验证的话，登录vip账号可否通过验证？

**Comment by duan602728596** [comment]
> > 现在不确定超清的直播地址和是否验证vip。
> 
> 如果需要验证的话，登录vip账号可否通过验证？

现在需要vip账号抓包拿到超清的直播地址

**Comment by mskgroup** [comment]
> > > 现在不确定超清的直播地址和是否验证vip。
> > 
> > 
> > 如果需要验证的话，登录vip账号可否通过验证？
> 
> 现在需要vip账号抓包拿到超清的直播地址

希望可以增加本功能，非常感谢！另，请问哪里可以下载到每日编译版本？

**Comment by mskgroup** [comment]
> > > 现在不确定超清的直播地址和是否验证vip。
> > 
> > 
> > 如果需要验证的话，登录vip账号可否通过验证？
> 
> 现在需要vip账号抓包拿到超清的直播地址

您好，我登录vip账号后，选择超清下载时仍提示需要vip账号
