### ISSUE TITLE
请问ACFUN的视频下载支持列表下载吗？

### ISSUE THREAD

**Issue by jmantnt** [duan602728596/48tools#108]
我是因为需要下载ACFUN的一个合集资源找到本软件的，安装完成后确实可以下载视频！在这里感谢作者的付出，软件开发不易特别是这种没有收入的事情，但是我遇到一个问题，因为我需要下载合集里面的视频，一共240P。。。。一个一个去打开再复制ID确实很麻烦，请问有简单点的方法吗。。。再次谢谢作者～～～

**Comment by duan602728596** [comment]
暂时还没有列表，我看一下。
