### ISSUE TITLE
部分公演录播下载完成后时间轴有问题

### ISSUE THREAD

**Issue by MalhelaCN** [duan602728596/48tools#11]
下载好的公演录播,有一部分时间不对,用各种播放器打开后时长都只有几分钟.
本地重新下载会复现
用其他下载软件使用output目录下的m3u8文件进行下载,下载完成的文件没有问题

**Comment by duan602728596** [comment]
我刚才试了一下，也是有问题。甚至用ffmpeg本地下载m3u8，也失败了。所以我怀疑这是48的录播源有问题。因为软件里面的依赖我已经很久没动过了，而以前还是好使的。
