### ISSUE TITLE
发送弹幕

### ISSUE THREAD

**Issue by tdzz1102** [duan602728596/48tools#112]
## 这个功能解决了什么问题？

发送弹幕

## 你期望的功能是怎样的？

在观看直播的界面中显示弹幕区域下面增加一个input组件发送弹幕，完全解放手机端

## 疑问

我用ios口袋48+charles proxy抓包抓不到发送弹幕的接口，请问一下有人知道发送弹幕的通信方式吗？

**Comment by duan602728596** [comment]
不好实现，会被滥用。以前别人做过，后来也关闭了。
