### ISSUE TITLE
微博超话签到功能获取不到cookie

### ISSUE THREAD

**Issue by wintopic** [duan602728596/48tools#116]
## 错误报告

微博超话签到功能获取不到cookie，登录后关闭窗口，无法正确添加账号。

## 复现步骤

微博超话签到-微博账号登录-微博登录-立即登录-手机号+验证码登录-关闭窗口-无法正常添加cookie
（已正确添加无头浏览器配置）

## 预期行为

希望可以继续正常登录使用，真的很方便🙂。

## 使用环境

版本	Windows 11 专业版 Insider Preview
版本号	24H2
安装日期	‎4/‎20/‎2024
操作系统版本	26200.5001
体验	Windows Feature Experience Pack 1000.26200.5001.0

**Comment by duan602728596** [comment]
这个登录方式已经去掉了，换另一种登录方式。
