### ISSUE TITLE
直播看不到弹幕了

### ISSUE THREAD

**Issue by ssss3344434** [duan602728596/48tools#118]
## 错误报告

看不到弹幕了

## 复现步骤

直接打开直播间 看不到弹幕

## 预期行为
以前是有弹幕的

## 使用环境

- 操作系统：win11
- 软件版本：4.11.1.0

**Comment by shiningPrince1003** [comment]
补充细节：
因为无法进入直播chatroom，所以没有弹幕。
以下是NIM的sdk报错
{
    "message": "login error: 非法操作或没有权限",
    "code": 403,
    "timetag": 1715660194514,
    "event": {},
    "callFunc": "protocol::parseResponse: 13_2",
    "cmd": "login",
    "retryCount": 0,
    "willReconnect": false
}

**Comment by duan602728596** [comment]
由于直播弹幕使用的SDK的权限问题，暂时会移除弹幕功能。
