### ISSUE TITLE
直播录制可以设置为录制为mp4格式视频吗

### ISSUE THREAD

**Issue by Cansiny0320** [duan602728596/48tools#12]
flv格式的话还要经过转码为MP4格式才能进行剪辑

**Comment by duan602728596** [comment]
现在不支持，因为视频源是flv的。如果转换成mp4格式，在直播的过程中如果终止，会造成格式损坏，视频无法播放的情况。

**Comment by Cansiny0320** [comment]
你好 我试验了几次之后 发现直接使用ffmpeg命令 `ffmpeg -i input.flv -vcodec copy -acodec copy output.mp4` 将录制的flv文件封装为mp4文件也可以进行剪辑 可不可以根据这个添加个录制完后自动转mp4功能呢

**Comment by duan602728596** [comment]
你用的什么软件剪辑？pr吗？

**Comment by Cansiny0320** [comment]
对的 只不过在直播卡顿的时候会出现封装后音画不同步的现象

**Comment by duan602728596** [comment]
转换的话，裁剪功能也可以转换，直接输出mp4文件就可以了，就是你的那个命令。
不过那个命令转换后，用pr剪辑还是会出现不同步的现象，因为转换出来的码流还是有问题。不同步的问题需要更高级的软件来解决（不是格式工厂，因为格式工厂本质上也是调用的ffmpeg）。
