### ISSUE TITLE
聚聚能抓取小偶像房间公开语音吗

### ISSUE THREAD

**Issue by shouyeshouye** [duan602728596/48tools#121]
我在手机上查找口袋48的文件目录，找了好久都没找到小偶像的语音缓存数据，聚聚是否知道语音数据缓存在哪个文件夹？（安卓系统）

**Comment by duan602728596** [comment]
？语音不在文件夹里，有静态资源地址，要自己下载。

**Comment by shouyeshouye** [comment]
是房间语音哦 只有几秒钟那种。
静态资源地址如何获取？在log文件中吗？

**Comment by duan602728596** [comment]
有例子吗？

**Comment by shouyeshouye** [comment]
![微信图片_20240713153736](https://github.com/user-attachments/assets/cf0d3a89-d42c-49ea-85f1-5ffbdd21b808)
就这种语音哇。

**Comment by duan602728596** [comment]
房间语音有资源地址，需要自己下载。音频地址可以手机抓包获得。而且软件很早就已经支持视频和语音文件了。
