### ISSUE TITLE
B站直播抓取问题

### ISSUE THREAD

**Issue by Nothatcold07** [duan602728596/48tools#13]
大佬好，我发现最近版本的48tools 
B站直播抓取的时候 ，只能录制到1280*720这个画质，以前的一些版本倒是可以抓到1080P的。
不知道是什么原因

**Comment by duan602728596** [comment]
有可能是B站换源了。因为B站在登陆和未登陆的时候，返回的原画的直播地址不一样，ffmpeg无法抓取登陆后的直播地址。当然，也不排除sb降画质的可能。

**Comment by duan602728596** [comment]
最新的版本已经带B站的扫码登陆功能，可以尝试一下
