### ISSUE TITLE
请问有可能下载lrc弹幕文件吗

### ISSUE THREAD

**Issue by spicaember** [duan602728596/48tools#14]
有看到QQ内的机器人会解析出lrc弹幕文件，类似这样的
https://source.48.cn/live/lrc/20200615/ae1dea84-5c32-443d-bdd9-a129690f0652.lrc
请问有办法在下载回放的同时也一并下载这个文件吗（或解析弹幕文件的地址）

**Comment by duan602728596** [comment]
弹幕文件可以下载，但是解析需要你自己来处理

**Comment by duan602728596** [comment]
最新版本添加了下载弹幕文件的功能
