### ISSUE TITLE
录播文件命名方式

### ISSUE THREAD

**Issue by longying506** [duan602728596/48tools#17]
能不能在录播文件保存的时候自动添加上【直播标题-时间】这部分呢，lrc的命名目前只能手动改吗？

**Comment by duan602728596** [comment]
可以加上时间，lrc也可以和录播统一。之前没加标题的原因是因为怕直播标题里有特殊字符，不过才想起来可以手动修改，可以加上了

**Comment by longying506** [comment]
是你那边直接在线更新吗？

**Comment by longying506** [comment]
> 可以加上时间，lrc也可以和录播统一。之前没加标题的原因是因为怕直播标题里有特殊字符，不过才想起来可以手动修改，可以加上了

是你那边直接在线更新吗？

**Comment by duan602728596** [comment]
> > 可以加上时间，lrc也可以和录播统一。之前没加标题的原因是因为怕直播标题里有特殊字符，不过才想起来可以手动修改，可以加上了
> 
> 是你那边直接在线更新吗？

等我这周把A站的直播加上就发版，不是在线更新

**Comment by longying506** [comment]
> > > 可以加上时间，lrc也可以和录播统一。之前没加标题的原因是因为怕直播标题里有特殊字符，不过才想起来可以手动修改，可以加上了
> > 
> > 
> > 是你那边直接在线更新吗？
> 
> 等我这周把A站的直播加上就发版，不是在线更新

好的，感谢！

**Comment by duan602728596** [comment]
已发版
