### ISSUE TITLE
48tools-v3.1.0-win下载不了口袋48XOX录播

### ISSUE THREAD

**Issue by mayuyu1990** [duan602728596/48tools#18]
大大为什么我下载不了口袋48XOX录播，显示下载失败，我是win10 64位系统
![捕获](https://user-images.githubusercontent.com/77672896/105030441-c01e5000-5a8e-11eb-8a2a-fa1d91bf4a9a.PNG)

**Comment by LeonJust** [comment]
ffmpeg配置好了么

**Comment by duan602728596** [comment]
先配置ffmpeg的文件地址

**Comment by LeonJust** [comment]
已经用了一段时间了，非常好用，感谢大牛聚聚
