### ISSUE TITLE
聚聚写软件辛苦了。可我认为可以把“成员直播录源”这个功能删掉。

### ISSUE THREAD

**Issue by NIC12345** [duan602728596/48tools#2]
因为，成员在直播完了之后可以自己删除不合适的录播。
比如直播出现了走光，无意说了脏话；
还有特别是一时兴起不严肃的唱起了国歌；还有对历史的不知道，比如有个成员说她爸有点支持希特勒。
这要是发到B站被哪个有心人士看见了，就不好了。
综上所述，希望考虑考虑把“成员直播录源”这个功能删掉。

**Comment by BEJ48** [comment]
> 录源这个功能其实主要是应援会需要的，需要做cut传到B站的，所以有了录源这个功能。

应援会也不可能完全审核的。他们也可以只拿“录播下载”的视频来剪cut啊。我也是有感而发，有主播因为乱唱国歌被禁了，虽然出错的几率很小，可万一以后被拿出来鞭尸。我只是路过的，随便说说。不要嫌我啰嗦。

**Comment by duan602728596** [comment]
这样的话，我添加个提示吧。录播的视频因为编码的原因，做cut会有编码问题。

**Comment by BEJ48** [comment]
> 这样的话，我添加个提示吧。录播的视频因为编码的原因，做cut会有编码问题。

打扰你了，有劳你了。为了48！为了小偶像！
