### ISSUE TITLE
服务器上无法进行下载录制

### ISSUE THREAD

**Issue by TN2win** [duan602728596/48tools#20]
window版，一点击录制和下载就自动取消，不产生ts文件，只产生m3u8文件

**Comment by duan602728596** [comment]
先配置ffmpeg文件的地址

**Comment by TN2win** [comment]
已配置



---原始邮件---
发件人: "B.B.K.K.B.K.K（段昊辰）"<notifications@github.com&gt;
发送时间: 2021年3月3日(周三) 下午3:01
收件人: "duan602728596/48tools"<48tools@noreply.github.com&gt;;
抄送: "TN2win"<1119144321@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [duan602728596/48tools] 服务器上无法进行下载录制 (#20)




 
先配置ffmpeg文件的地址

**Comment by duan602728596** [comment]
配置完也无法下载吗？你先试试本地下载

**Comment by TN2win** [comment]
本地没问题



---原始邮件---
发件人: "B.B.K.K.B.K.K（段昊辰）"<notifications@github.com&gt;
发送时间: 2021年3月3日(周三) 下午3:14
收件人: "duan602728596/48tools"<48tools@noreply.github.com&gt;;
抄送: "TN2win"<1119144321@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [duan602728596/48tools] 服务器上无法进行下载录制 (#20)




 
配置完也无法下载吗？你先试试本地下载

**Comment by duan602728596** [comment]
那就有可能是ffmpeg缺了依赖库，可以去官网下载个新的试试。

**Comment by TN2win** [comment]
更换最新版的ffmepg后可以使用，问题解决。
顺便问一下，qqtools里面桃叭集资代码可以弄与上一个人的差距吗？目前我看显示的是与目标的差距。还有，可能添加抽卡功能吗？
谢谢大佬。



---原始邮件---
发件人: "B.B.K.K.B.K.K（段昊辰）"<notifications@github.com&gt;
发送时间: 2021年3月3日(周三) 下午3:27
收件人: "duan602728596/48tools"<48tools@noreply.github.com&gt;;
抄送: "TN2win"<1119144321@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [duan602728596/48tools] 服务器上无法进行下载录制 (#20)




 
那就有可能是ffmpeg缺了依赖库，可以去官网下载个新的试试。

**Comment by duan602728596** [comment]
什么叫与上一个人的差距

**Comment by TN2win** [comment]
也就是如果设立PK，和对方的差距
或者设立多人PK，和比自己多钱的那一位的差距



---原始邮件---
发件人: "B.B.K.K.B.K.K（段昊辰）"<notifications@github.com&gt;
发送时间: 2021年3月3日(周三) 下午4:08
收件人: "duan602728596/48tools"<48tools@noreply.github.com&gt;;
抄送: "TN2win"<1119144321@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [duan602728596/48tools] 服务器上无法进行下载录制 (#20)




 
什么叫与上一个人的差距

**Comment by TN2win** [comment]
再顺便问一下大佬
b站上有可能有自动抓取吗。😃



---原始邮件---
发件人: "B.B.K.K.B.K.K（段昊辰）"<notifications@github.com&gt;
发送时间: 2021年3月3日(周三) 下午4:08
收件人: "duan602728596/48tools"<48tools@noreply.github.com&gt;;
抄送: "TN2win"<1119144321@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [duan602728596/48tools] 服务器上无法进行下载录制 (#20)




 
什么叫与上一个人的差距
