### ISSUE TITLE
linux版无法打开

### ISSUE THREAD

**Issue by onlyzqy** [duan602728596/48tools#22]
试图运行的时候提示无法定位程序，无法打开，向大佬求教

**Comment by duan602728596** [comment]
有截图吗？我这边没有linux系统，我也没发保证linux的会不会有问题

**Comment by onlyzqy** [comment]
![2021-03-16 19-36-04 的屏幕截图](https://user-images.githubusercontent.com/44560939/111303176-34d8c980-868f-11eb-82a0-7403bf175d0b.png)
打开的时候是这样的
![2021-03-16 19-39-01 的屏幕截图](https://user-images.githubusercontent.com/44560939/111303269-4a4df380-868f-11eb-90b5-700a8bd2b5af.png)
运行文件的属性是这个情况

**Comment by duan602728596** [comment]
你需要通过命令行来启动这个软件
