### ISSUE TITLE
v3.40 v3.50 winx64版口袋直播播放界面空白

### ISSUE THREAD

**Issue by sde31c** [duan602728596/48tools#23]
v3.40和v3.50版口袋48直播播放界面空白。
同一网络条件下，v3.30版可正常进行直播播放。
![Snipaste_2021-03-25_15-08-28](https://user-images.githubusercontent.com/21274744/112432532-025c5a00-8d7c-11eb-9847-7905d05e529d.png)

**Comment by duan602728596** [comment]
等我晚上编译发版

**Comment by duan602728596** [comment]
已发版
