### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by lanfeng-shui** [duan602728596/48tools#24]
使用”口袋48录播下载-下载图片“功能时，若在仅有一张图片的情况下选择了“下载全部图片到文件夹”会导致在下载路径生成一个无法打开、无法删除的空文件夹，且图片未被下载，求助生成的文件夹如何删除。[
![屏幕截图(11)](https://user-images.githubusercontent.com/81756923/114121733-7b81b280-9921-11eb-8a56-9d84add5eef7.png)
![屏幕截图(10)](https://user-images.githubusercontent.com/81756923/114121760-8a686500-9921-11eb-8a7a-ccee7a9f4789.png)

](url)

**Comment by duan602728596** [comment]
感觉你这个是权限的问题
