### ISSUE TITLE
关于token和pa

### ISSUE THREAD

**Issue by 2608019886** [duan602728596/48tools#26]
能请教下老哥pa以及token是怎么获取的吗？感谢

**Comment by duan602728596** [comment]
手机抓包，在请求头中有token和pa。
token是账号登陆后返回的，pa是算出来的，算法未知。

**Comment by 2608019886** [comment]
> 马德·科布特·巴金·巴
> 令牌的卡普·卡德·金德·帕里特·巴金

好的，谢谢
