### ISSUE TITLE
大佬，口袋48直播抓取一直在转圈是什么问题？

### ISSUE THREAD

**Issue by AsahiOtome** [duan602728596/48tools#27]
使用口袋48的直播抓取时，操作选播放会一直在开始界面转圈了，不过复制直播地址再打开是可以用本地播放的，这是什么问题呢？

**Comment by duan602728596** [comment]
你配置ffmpeg了吗？直播抓流需要ffmpeg，而且配置完后需要重新启动

**Comment by duan602728596** [comment]
#31

**Comment by qp9632** [comment]
MAC版怎么配置，连接那两个ffmpeg下载下来之后怎么做，小白
