### ISSUE TITLE
成员的直播录播下载

### ISSUE THREAD

**Issue by KelvinSoh8** [duan602728596/48tools#28]
关于，成员的直播录播下载，希望可以，支持选，某位成员的录播历史，支持全部下载，成员之前，的录播，或者，可以导出m3u8下载地址，比如我选着A成员，然后可以批量下载，A成员的历史录播视频，我想收藏嘛

**Comment by duan602728596** [comment]
等我嘉兴路休假回来的就加

**Comment by duan602728596** [comment]
已发版
