### ISSUE TITLE
一直显示在直播录播状态

### ISSUE THREAD

**Issue by kybom** [duan602728596/48tools#3]
48tools  v1.5.7
一直显示在直播录播中，实际已经没有直播了，从1月18号开始，今天是1月22号，见下图
![qq 20190122100557](https://user-images.githubusercontent.com/24692485/51510266-6818c880-1e37-11e9-9da9-55f2c7bd0008.png)

在目录中没有看到相关日志，请问遇到这种情况有办法定位问题吗？

**Comment by kybom** [comment]
> 因为这个录制调用的是ffmpeg，ffmpeg如果在录制的过程中因为网络等原因卡住的话，就无法结束这个进程。我这边是为了避免自动录制的时候，直播已经结束，而录制没结束，而没法处理，所以直播结束而录制没结束的进程都是橘黄色的。

为什么点击“停止录播”可以结束？

**Comment by duan602728596** [comment]
停止录播是直接结束了调用ffmpeg的命令行的进程




| |
段昊辰
邮箱：duanhaochen@126.com
|

签名由 网易邮箱大师 定制

在2019年06月26日 18:30，kybom 写道：

因为这个录制调用的是ffmpeg，ffmpeg如果在录制的过程中因为网络等原因卡住的话，就无法结束这个进程。我这边是为了避免自动录制的时候，直播已经结束，而录制没结束，而没法处理，所以直播结束而录制没结束的进程都是橘黄色的。

为什么点击“停止录播”可以结束？

**Comment by kybom** [comment]
可以用另一个进程监控录播进程吗？直播结束了后，超时一定时间仍在录播就让它结束。

**Comment by duan602728596** [comment]
超时一般是因为直播结束但是这边没下完，超时太多的是因为ffmpeg下载出现的问题，这个我没法确定
