### ISSUE TITLE
Mac intel 环境 3.7.0 一打开就会报错

### ISSUE THREAD

**Issue by SauceWu** [duan602728596/48tools#32]
Mac intel 环境 3.7.0 一打开就会报错
Uncaught Exception:
Error: Cannot find module 'node-media-server'
Require stack:
- /private/var/folders/5s/4fyk1thd48z1x60pv9ykz3mh0000gn/T/AppTranslocation/AC1465FD-72BE-4876-9CAD-240D8F1B22B0/d/48tools.app/Contents/Resources/app.asar.unpacked/bin/lib/nodeMediaServer/server.worker.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
at Function.Module._load (internal/modules/cjs/loader.js:737:27)

**Comment by duan602728596** [comment]
应该是asar的问题，等我处理一下，可以先用旧版。
