### ISSUE TITLE
3.7 打开报错，直播无法观看

### ISSUE THREAD

**Issue by KOUymA** [duan602728596/48tools#33]
## 错误报告

![image](https://user-images.githubusercontent.com/72074577/126868865-3f9d7c6f-c7ee-4f4a-8d5e-6cc7c21b6795.png)

## 复现步骤

打开就报错了，可以抓取直播但是无法观看

**Comment by duan602728596** [comment]
应该是asar的问题，等我处理一下，可以先用旧版。
