### ISSUE TITLE
请问如何搜索并下载某一个成员的所有直播回放

### ISSUE THREAD

**Issue by psps1029** [duan602728596/48tools#34]
在录播下载中，输入偶像名称搜索只能搜索下面加载列表里的，但是我看到成员id是可以检索出来，比如在成员id框里输入1，点击加载列表回显是张语格，显示出从2016年到今天的所有直播录像，那这个id到底怎么看，如果我要搜索另外一个成员，那这个数字id和成员名字是怎么匹配呢，望解答，只想下载部分成员的所有直播回放

**Comment by duan602728596** [comment]
偶像名称搜索只涉及到已加载的数据。

成员id名单：https://github.com/duan602728596/qqtools/blob/main/packages/NIMTest/node/roomId.json

**Comment by psps1029** [comment]
> 偶像名称搜索只涉及到已加载的数据。
> 
> 成员id名单：https://github.com/duan602728596/qqtools/blob/main/packages/NIMTest/node/roomId.json

    还有个新问题，今天下载都没有问题，刚刚发现下载的视频后缀.ts.m3u8，这是没有转码嘛，还是有限制了

**Comment by Fakerlovebang** [comment]
这个成员名单里面有几个我找不到，比如黄婷婷和冯薪朵
