### ISSUE TITLE
反馈下载的时候有个新问题

### ISSUE THREAD

**Issue by psps1029** [duan602728596/48tools#35]
今天下载一直没有问题，正常的是两个文件，一个ts视频文件，还有一个.ts.m3u8几十k的文件，刚刚突然发现新下载视频只有一个文件ts.m3u8，且大小为视频大小，这是没有转码吗，无法播放，配置的FFmpeg是没问题的，这是哪边有限制？

**Comment by duan602728596** [comment]
实测没有任何问题，视频名称和id

**Comment by psps1029** [comment]
> 实测没有任何问题，视频名称和id

请测试id 6738 宋昕冉 2019-03-04 20:51:31及时间更早的，我试了几个都不可以![mmexport1630287482410.png](https://user-images.githubusercontent.com/69746880/131273777-ca8de395-5165-4ebc-9ad0-07cbd018b786.png)

**Comment by psps1029** [comment]
请测试id 6738 宋昕冉 2019-03-04 20:51:31及时间更早的，我试了几个都不可以![mmexport1630287482410.png](https://user-images.githubusercontent.com/69746880/131295111-e2c318f4-c614-455e-b1d4-7e680689e636.png)
