### ISSUE TITLE
反馈一个直播下载问题

### ISSUE THREAD

**Issue by HibariSun** [duan602728596/48tools#37]
48tool [v3.73,已配置好ffmpeg文件，口袋直播录制播放等功能可以使用，但直播下载只有一个M3U8文件，而之前应该是有ts和m3u8两个文件的。
![微信图片_20210901221850](https://user-images.githubusercontent.com/79096889/131688907-dd2c44cd-81a1-4da8-9123-243f02908876.png)

**Comment by anjingyisheng** [comment]
朋友，我也是这个问题，是bug吗

**Comment by duan602728596** [comment]
录播视频现在用ffmpeg下载会出现403的问题，可能需要修改下载方法

**Comment by anjingyisheng** [comment]
修改下载方法，怎么弄
