### ISSUE TITLE
下载录播时只有一个.ts.m3u8文件

### ISSUE THREAD

**Issue by psps1029** [duan602728596/48tools#38]
开发者大大我又来反馈问题了，版本是最新版3.7.3，目前下载录播视频只有一个几十kb的.ts.m3u8文件，点击可播放，显示有几百个ts文件陆续播放，应该是没有合并为单个文件，这个是ffmgeg的问题吗？但是之前下载是正常的，ffmgeg配置也没有问题，下图
![mmexport1630585886889.png](https://user-images.githubusercontent.com/69746880/131844022-20f92c65-870d-445e-9615-7dc0ba4e08d8.png)![mmexport1630585889994.png](https://user-images.githubusercontent.com/69746880/131844032-c1e63898-f6e0-4c22-8d3b-dc5016552de3.png)![mmexport1630585892994.png](https://user-images.githubusercontent.com/69746880/131844050-c7a4e4a2-0f4b-4dfc-babb-c9e6e77bfe24.png)

**Comment by duan602728596** [comment]
#37 已发版
