### ISSUE TITLE
反馈下载录播问题

### ISSUE THREAD

**Issue by psps1029** [duan602728596/48tools#39]
下载过程中，文件夹里分段的视频有大概率在某一段变成0k，无法继续下载，在界面上一直是正在下载的状态，但实际上不会下载了![mmexport1630823251827.png](https://user-images.githubusercontent.com/69746880/132117800-e23e8d24-3aed-4843-9b9e-744dee400c79.png)![mmexport1630823255114.png](https://user-images.githubusercontent.com/69746880/132117804-c17e1e86-097a-4b6a-85e0-6c935ff8cf0d.png)

**Comment by 294880776** [comment]
一样遇到了这个问题

**Comment by psps1029** [comment]
是更新新版本嘛
