### ISSUE TITLE
48tools怎么升级？

### ISSUE THREAD

**Issue by kybom** [duan602728596/48tools#4]
我现在用的是1.5.7版，现在想升级到1.6版本，是解压后直接覆盖吗？

**Comment by duan602728596** [comment]
@kybom 旧的版本删掉，下载新版本直接用就可以了，配置什么的都还在的。

**Comment by kybom** [comment]
文件是保存在旧版本output里面，不能删。大概有1个T，也不好转移到新版本output。

**Comment by duan602728596** [comment]
@kybom 你把除了output的都删了就行，然后把新的拷贝过来，文件夹合并
