### ISSUE TITLE
自动录制时，在连麦后丢失画面，只有声音

### ISSUE THREAD

**Issue by Hz007** [duan602728596/48tools#44]
在开始连麦之后画面全部丢失，只录下了声音，视频时长短于音频时长。这种情况有什么办法解决吗？
Eg. 直接用potplayer播放flv文件发现时长为1h，分离音频后发现音频时长为2h，只是1-2h部分没有画面了

**Comment by Hz007** [comment]
您好，这里是自动回复。我已收到您的邮件，谢谢。

**Comment by duan602728596** [comment]
连麦不太好处理，因为我不清楚连麦后的流的变化
