### ISSUE TITLE
口袋48录播下载现在无法通过成员id搜索了

### ISSUE THREAD

**Issue by psps1029** [duan602728596/48tools#48]
任何成员的id都无法搜索了，点击加载列表无法出现单个成员的录播![mmexport1652691365603.png](https://user-images.githubusercontent.com/69746880/168556322-19482c3f-7b08-4cc5-a197-6bca02be9ee1.png)

**Comment by duan602728596** [comment]
现在App上已经不支持了，所以我也无法解决。请向48官方反馈。
