### ISSUE TITLE
2022.8.8的录播试了很多个都无法下载

### ISSUE THREAD

**Issue by lanfeng-shui** [duan602728596/48tools#51]
## 错误报告
2022.8.8的录播试了很多个都无法下载，尝试更换网络，换电脑，重新下载软件都不行，但是口袋里面录播是正常的
![Screenshot (4)](https://user-images.githubusercontent.com/81756923/183459233-e8579125-9492-479f-9b77-c85e25930f73.png)

## 复现步骤
录播无法下载
![Screenshot (4)](https://user-images.githubusercontent.com/81756923/183459187-e805c0eb-6bbc-459b-9fd1-e7623e4b4c2b.png)

## 预期行为
麻烦大佬看一下是哪里出问题了 辛苦啦

## 使用环境
- 操作系统：win11 64
- 软件版本：3.12.0

**Comment by lanfeng-shui** [comment]
不知道是不是用户代理的问题

**Comment by longgu2021** [comment]
口袋回放网页版也是加载不出来了  好像是软件给关掉了

**Comment by lanfeng-shui** [comment]
对的 网页版也无法播放了 不知道咋解决 > 口袋回放网页版也是加载不出来了  好像是软件给关掉了

**Comment by duan602728596** [comment]
静态资源目前会返回403 Forbidden Error.

**Comment by will94king** [comment]
所以这个问题是可以被修复的吗？聚聚们辛苦了

**Comment by anjingyisheng** [comment]
大佬，那个3.12.1新版本的48tools网页上下载速度太慢了，能否在百度网盘里上传一份
