### ISSUE TITLE
直播下载的时候出现了这个报错，大佬能帮忙看看吗

### ISSUE THREAD

**Issue by will94king** [duan602728596/48tools#55]
## 错误报告

![image](https://user-images.githubusercontent.com/45196786/184501016-6958b666-456c-4e5d-8b50-7ef5920f2eca.png)

## 复现步骤

下载了一下之后出现了这个报错

## 预期行为

正常下载

## 使用环境

- 操作系统：windows 10
- 软件版本：3.12.1

**Comment by duan602728596** [comment]
是有一些问题，我修复一下看看

**Comment by lanfeng-shui** [comment]
> 是有一些问题，我修复一下看看

我也遇到了这个问题，而且还是存在录播下不动的情况

**Comment by frappuccino111** [comment]
提示录播下载失败
请问也是一样的问题吗  感谢
![48tools - 3 9 2 2022_8_14 12_41_59](https://user-images.githubusercontent.com/111214030/184522834-52e60159-9a9a-49ed-9e6b-8ec4b255f272.png)
！

**Comment by duan602728596** [comment]
> 提示录播下载失败 请问也是一样的问题吗 感谢 ![48tools - 3 9 2 2022_8_14 12_41_59](https://user-images.githubusercontent.com/111214030/184522834-52e60159-9a9a-49ed-9e6b-8ec4b255f272.png) ！

不是
