### ISSUE TITLE
建议增加错误提示

### ISSUE THREAD

**Issue by kybom** [duan602728596/48tools#6]
比如今天口袋后台更新维护，这个圈一直在这转,代表一直尝试，还是只尝试了一次？
![QQ截图20190415151934](https://user-images.githubusercontent.com/24692485/56113934-f19cea00-5f91-11e9-9eec-e76519b48732.png)

**Comment by duan602728596** [comment]
应该是一直在尝试，没加超时时间

**Comment by kybom** [comment]
我点返回，在进入这个页面，没有再看到请求相关的信息，默认是一分钟请求一次。
