### ISSUE TITLE
房间消息抓取

### ISSUE THREAD

**Issue by youkoulc** [duan602728596/48tools#64]
1. 目前只能抓取到22年4月1日之后的数据，还有可能能获取到更早的吗？
2. 目前导出的数据是json格式，未来会推出更方便直接查看的格式吗，比如pdf
3. 主要目的是想看看xox之前的发言记录，应该会有一些蛮有意思的发言，糊糊也没有应援会记录这些

**Comment by duan602728596** [comment]
1. 获取不到，没有的数据就是没了。这是那边的问题，不在我这里。
2. 可以考虑。主要是格式化所有的数据类型是很麻烦的事情。

**Comment by duan602728596** [comment]
导出为html格式。pdf由于转换时间太长以及载入太慢的原因放弃。
