### ISSUE TITLE
在保存口袋房间数据时，发现和时间匹配不上

### ISSUE THREAD

**Issue by rewrho** [duan602728596/48tools#66]
![2Y (9DQX49@(O3S%ICDGZGP](https://user-images.githubusercontent.com/107667790/226087612-1ed469cf-81da-4c60-99c1-ca7918eda146.png)
![%E)E~~8P7$PC 2A235$BC43](https://user-images.githubusercontent.com/107667790/226087631-4452daa7-a8c8-4f38-aa08-7bf89472d9e6.png)
就是这样，不知道为什么保存之后的时间都成一样的了

**Comment by duan602728596** [comment]
这是谁？

**Comment by rewrho** [comment]
高蔚然

**Comment by rewrho** [comment]
是修复好啦吗？

**Comment by duan602728596** [comment]
> 是修复好啦吗？

正在发版呢

**Comment by rewrho** [comment]
好的好的，麻烦您了

**Comment by rewrho** [comment]
我还有一个小小的问题，就是可不可以在下载电台时，把背景图也带上呢

**Comment by duan602728596** [comment]
已发版。背景图其实可以单独下载。

**Comment by rewrho** [comment]
![image](https://user-images.githubusercontent.com/107667790/226088798-f477f7aa-748a-443c-9a34-ff986f5d14f6.png)
![image](https://user-images.githubusercontent.com/107667790/226088848-0cee6a05-8276-4ef1-9a6c-5f2a40fe877e.png)
![image](https://user-images.githubusercontent.com/107667790/226088890-5c8d3b5e-be26-4554-b4f6-259c0e213cc4.png)
![image](https://user-images.githubusercontent.com/107667790/226088911-f3c17d7b-32d8-453d-826b-1c8052602ad0.png)
![image](https://user-images.githubusercontent.com/107667790/226088935-2b40c587-a630-49ef-9191-073b048eca41.png)
![image](https://user-images.githubusercontent.com/107667790/226088955-ddd8382a-f6ab-4401-b5ee-15a65f3705cc.png)
如果我从tools里找到话，在我加载数据后，这个直播内容是重复的

**Comment by rewrho** [comment]
所以我都是在这里：https://48tools.vercel.app/去下载，但是这样的话就不能单独下载背景图了

**Comment by duan602728596** [comment]
这只是标题重复吧

**Comment by rewrho** [comment]
没有，是真的重复了

**Comment by duan602728596** [comment]
奥，发现了，这是口袋api的bug

**Comment by rewrho** [comment]
嗯，那这可以修复吗

**Comment by duan602728596** [comment]
我想想怎么修，因为第一次加载会带出无关的数据。

**Comment by rewrho** [comment]
嗯，那麻烦老师你了

**Comment by duan602728596** [comment]
好吧，是我的问题，忘记判断next的值了，再发一次版。

**Comment by rewrho** [comment]
老师怎么样了

**Comment by duan602728596** [comment]
> 老师怎么样了
> 
> 

已经发版了

**Comment by rewrho** [comment]
重新打开tool就好了是吗

**Comment by duan602728596** [comment]
> 重新打开tool就好了是吗
> 
> 

额，需要重新下载。

**Comment by rewrho** [comment]
哦好的

**Comment by rewrho** [comment]
这两个问题都解决了，但是老师我又有一个新的问题就是：在我查看比较早期的直播录像时无法播放，就像这样：
![image](https://user-images.githubusercontent.com/107667790/226093732-67c67a04-3c94-4481-93d1-22a69a3ed81f.png)
请问该如何解决？
真是太麻烦老师了

**Comment by duan602728596** [comment]
几几年的？

**Comment by rewrho** [comment]
![image](https://user-images.githubusercontent.com/107667790/226095703-290e8005-be62-4a6c-8369-b344768d819c.png)
果然是因为时间太久远了吗

**Comment by rewrho** [comment]
我又有个疑问就是：口袋房间消息抓取好像这是包含一个房间的信息，就是我看没有保存另一个房间的消息

**Comment by duan602728596** [comment]
#67

**Comment by rewrho** [comment]
老师老师还有这个问题：口袋房间消息抓取好像只是包含一个房间的信息，没有保存另一个房间的消息

**Comment by duan602728596** [comment]
另一个房间先不考虑，有些会因为鸡腿条件或者问题显得有点私密。绕过去会不太好。
