### ISSUE TITLE
会增加上麦功能的录制吗

### ISSUE THREAD

**Issue by akiaki1996** [duan602728596/48tools#69]
## 录制上麦时的语音？

之前口袋新增了上麦功能，请问会有机会在48tools中添加一个上麦的录制功能吗？

**Comment by duan602728596** [comment]
上麦是啥？这个版本新加的吗？

**Comment by akiaki1996** [comment]
> 上麦是啥？这个版本新加的吗？

加入了有一段时间了，就是成员在口袋房间里直接语音，不同于电台需要开启直播推流（不过我不确定上麦有没有真正的推流，但是至少它不是通过直播形式来实现的）。上麦是成员直接在房间里开启语音，其他人直接在房间里发言进行互动。在上麦的时候房间右上角可以看到上麦的提示，并且可以完成多位成员连麦互动。

**Comment by akiaki1996** [comment]
ios 7.0.0版本更新日志里写到了：增加语聊功能，这个应该就是上麦了

**Comment by shiningPrince1003** [comment]
上麦功能的流与直播近似，是一个rtmp流，不过不会在直播列表出现。 从/im/api/v1/team/voice/operate 这里可以获取流。从QChat层抓包 可能 有更好的效果。
