### ISSUE TITLE
口袋信息保存

### ISSUE THREAD

**Issue by rewrho** [duan602728596/48tools#70]
老师我想问一下，就是我把口袋信息以html格式保存后，当口袋房间被关闭后，这个html还能打开吗？也就是信息还在吗

**Comment by duan602728596** [comment]
可以，html里没有任何fetch。保存成html只是为了方便查看，没有选择pdf是因为保存慢载入慢。

**Comment by rewrho** [comment]
那请问如何将这个html本地化保存啊

**Comment by duan602728596** [comment]
现在不就是本地化么？双击就能看

**Comment by rewrho** [comment]
双击打开后不是在一个网页上展示出来的吗？

**Comment by duan602728596** [comment]
这不就是能看了吗？

**Comment by rewrho** [comment]
就是想要进行上传的话，需要本地文件呀

**Comment by duan602728596** [comment]
上传什么？

**Comment by rewrho** [comment]
将这个口袋信息上传到平台

**Comment by rewrho** [comment]
或者说当我处于离线时，我不就不能查看了吗

**Comment by duan602728596** [comment]
离线也可以看啊

**Comment by rewrho** [comment]
![G}NC`B4`VQ`J1JMD3YUOIE1](https://user-images.githubusercontent.com/107667790/226283138-cb04b8df-0c22-45e1-9f6a-d5f4233c6e00.png)
![MO5 LU$55%%$62`9U7L$~36](https://user-images.githubusercontent.com/107667790/226283152-9381b5ab-3641-4139-997a-2a73b7dbae16.png)
离线看不了呀老师

**Comment by duan602728596** [comment]
双击打开的是本地文件，不会出现这个东西的。

**Comment by rewrho** [comment]
是可以正常看到聊天记录的，但是视频和图片看不到了...

**Comment by duan602728596** [comment]
视频图片都不在我这啊，我这里是不会处理这些东西的。

**Comment by rewrho** [comment]
也就说在离线状态下确实没办法看到视频和图片呗...

**Comment by duan602728596** [comment]
这些也不在我这里，我也没法控制它啊

**Comment by rewrho** [comment]
哦好吧，就这样吧，麻烦老师了
