### ISSUE TITLE
口袋房间消息-礼物消息未能正常显示

### ISSUE THREAD

**Issue by lanfeng-shui** [duan602728596/48tools#73]
## 错误报告

![image](https://user-images.githubusercontent.com/81756923/232178356-7bfe57cb-5377-46a0-b68a-43cfd590ce1a.png)

## 复现步骤

口袋房间消息-加载数据-导出当前数据为HTML

## 预期行为

消息导出为html格式时礼物消息正常显示

## 使用环境

- 操作系统：Win11 Pro x64
- 软件版本：3.20.2

**Comment by duan602728596** [comment]
奥，这是当初有些类型没做解析，类型太多了解析不动了。

**Comment by lanfeng-shui** [comment]
好噢 辛苦了
