### ISSUE TITLE
口袋房间消息保存同时保存所有在线资源到本地

### ISSUE THREAD

**Issue by lanfeng-shui** [duan602728596/48tools#75]
## 这个功能解决了什么问题？

目前的房间消息保存功能保存后的html网页里的音频及视频资源还是从48服务器上加载的，48服务器删除这些资源之后就无法查看了。

## 你期望的功能是怎样的？

希望房间消息保存功能能同时保存所有在线资源到本地，如音频、视频等。

**Comment by duan602728596** [comment]
由于文件资源过多且不会缓存，请求到本地会对服务器照成压力。建议下载后用网页另存为来处理。

**Comment by lanfeng-shui** [comment]
下载后网页另存为无法保存视频/音频资源或者就是只有部分能保存到本地，目前不知道该如何处理 > 由于文件资源过多且不会缓存，请求到本地会对服务器照成压力。建议下载后用网页另存为来处理。

**Comment by duan602728596** [comment]
该功能已经上线，但是需要`--enable-48-room-message-local-message`命令行参数，并且配置无头浏览器才能使用。
参数是为了避免功能被滥用。无头浏览器是为了拦截并保存资源到本地。

**Comment by lanfeng-shui** [comment]
已更新并使用参数启动，点击HTML本地化让选了保存位置之后没有反应，也没有提示，已配置无头浏览器（chrome/edge都试了），系统是Windows 11 Pro 22H2.
![image](https://user-images.githubusercontent.com/81756923/236376421-f24b7d46-658d-4ddd-9e9d-908fe91507d5.png)
![image](https://user-images.githubusercontent.com/81756923/236376440-3946f5a9-ad5e-45e6-b761-0360143aeca8.png)

**Comment by duan602728596** [comment]
选的不是保存位置，是聊天记录的文件夹的位置。生成的新文件会在这个文件夹里。

**Comment by lanfeng-shui** [comment]
明白了，感谢！

**Comment by lanfeng-shui** [comment]
发现新的问题，HTML本地化下载的视频很多只下载了前几秒，并不完整，离线的时候只能播放前几秒/无法播放。语音目前没有一个个听完暂未发现。
![image](https://user-images.githubusercontent.com/81756923/236480144-65e7554b-5b9b-4003-a39d-39b9f3435dff.png)

**Comment by duan602728596** [comment]
看来媒体文件还要特殊处理

**Comment by duan602728596** [comment]
现在媒体文件直接下载，不拦截资源了
