### ISSUE TITLE
大佬直播咋下载不了哇

### ISSUE THREAD

**Issue by ximingdd** [duan602728596/48tools#76]
## 错误报告

![Uploading 3_CTY`M3C~T1O7`(}S0NSSE.png…]()

直播视频下载失败

## 使用环境

- 操作系统：w11
- 软件版本：3.20.6

**Comment by ximingdd** [comment]
![Uploading 3_CTY`M3C~T1O7`(}S0NSSE.png…]()

**Comment by ximingdd** [comment]
![3_CTY`M3C~T1O7`(}S0NSSE](https://user-images.githubusercontent.com/127623939/235737250-4bec6d94-9018-4b30-a745-a59a7d31b07c.png)

**Comment by ximingdd** [comment]
用备用方案下载也只有片段没有合成完整的视频

**Comment by duan602728596** [comment]
使用前先配置ffmpeg
