### ISSUE TITLE
能不能添加快手

### ISSUE THREAD

**Issue by yaoguainalitao** [duan602728596/48tools#77]

**Comment by duan602728596** [comment]
可以添加直播录制。
视频下载会有验证码和无头浏览器的判断，可能会不行。

**Comment by yaoguainalitao** [comment]
他的验证好像不是很频繁哦，如果可以的话可以考虑加上去哦。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 告白，花，狼 ***@***.***&gt;
发送时间: 2023年5月6日 20:41
收件人: duan602728596/48tools ***@***.***&gt;
抄送: yaoguainalitao ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [duan602728596/48tools] 能不能添加快手 (Issue #77)





 
可以添加直播录制。
 视频下载会有验证码和无头浏览器的判断，可能会不行。

**Comment by duan602728596** [comment]
不确定，也有可能和区域有关，看看国内有没有问题吧

**Comment by yaoguainalitao** [comment]
好的，非常感谢。祝您生活愉快



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 告白，花，狼 ***@***.***&gt;
发送时间: 2023年5月6日 20:47
收件人: duan602728596/48tools ***@***.***&gt;
抄送: yaoguainalitao ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [duan602728596/48tools] 能不能添加快手 (Issue #77)





 
不确定，也有可能和区域有关，看看国内有没有问题吧

**Comment by duan602728596** [comment]
已添加

**Comment by yaoguainalitao** [comment]
谢谢




°旅行的终点灬是你心底┓
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "duan602728596/48tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月8日(星期一) 凌晨1:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [duan602728596/48tools] 能不能添加快手 (Issue #77)





 
Closed #77 as completed.
