### ISSUE TITLE
4.0.1每次返回首页都会有新用户引导

### ISSUE THREAD

**Issue by QiuWeijin** [duan602728596/48tools#84]
## 使用环境

- 操作系统：win11
- 软件版本：4.0.1

**Comment by duan602728596** [comment]
打开开发者工具，在Application中，找Local storage，看一下USER_TOUR_VERSION的值是不是1。

**Comment by duan602728596** [comment]
你把这个值删除一下，重新走完所有引导试试呢？

**Comment by QiuWeijin** [comment]
> 
我把值改成0以后就没有再出现引导了，但是软件重启之后又会重新出现引导

**Comment by duan602728596** [comment]
那可能是之前取值有问题了。

**Comment by duan602728596** [comment]
升级Electron大版本后应该是修复了
