### ISSUE TITLE
B站視頻下載無法選擇分辨率

### ISSUE THREAD

**Issue by 21790EC** [duan602728596/48tools#87]
## 错误报告

掃碼登入b站帳號後，只要有選擇分辨率都會下載失敗
<img width="989" alt="截圖 2023-08-29 下午8 59 24" src="https://github.com/duan602728596/48tools/assets/61772507/45503a0b-902a-4f36-bf3e-1c292c7ab333">

不選擇分辨率都能成功下載1080p，
但BV1GW411T7ga不知為何只能下載360p／BV1HA4115767下載的檔案只有0 byte

## 复现步骤

请提供能够复现问题的步骤：
1. 掃碼登入b站
2. 添加下載任務
3. 選擇其他分辨率（任意）
4. 下載失敗

## 使用环境

- 操作系统：macOS Ventura 13.5.1
- 软件版本：4.2.1

**Comment by duan602728596** [comment]
我这边测试是可以正常下载的，你是否没有配置FFmpeg？你可以打开开发者工具，查询一下这个请求，看看日志显示的是什么。
<img width="359" alt="截屏2023-08-29 22 39 00" src="https://github.com/duan602728596/48tools/assets/17332657/4afa9e6b-c3a6-49cf-a5d0-9b159d9d9840">

**Comment by 21790EC** [comment]
有配置FFmpeg
請問要如何在開發者工具查詢？

我有試著再次下載BV1GW411T7ga的p3，開發者工具顯示以下畫面：
<img width="557" alt="截圖 2023-08-30 上午5 35 26" src="https://github.com/duan602728596/48tools/assets/61772507/22afbf27-4a4c-480f-80fa-d6ce8ce2d31e">
且下載的檔案只有0 byte

**Comment by duan602728596** [comment]
首页会有个扳手🔧图标，点击那个就是了。

**Comment by 21790EC** [comment]
不選擇分辨率時：
<img width="528" alt="截圖 2023-08-30 下午5 30 01" src="https://github.com/duan602728596/48tools/assets/61772507/f240cb7c-38bb-4c3c-98da-8a9291274f40">
檔案還是360p

但如果選擇分辨率：
<img width="530" alt="截圖 2023-08-30 下午5 29 52" src="https://github.com/duan602728596/48tools/assets/61772507/c5a52cab-71ee-4d32-aaee-f844cd83ca0b">
<img width="530" alt="截圖 2023-08-30 下午5 29 38" src="https://github.com/duan602728596/48tools/assets/61772507/b804d550-8d2e-43e0-9474-34909fa4c241">
同樣顯示下載失敗，且沒有任何檔案

以上都沒有顯示報錯

請問那個代理地址是指什麼？

**Comment by duan602728596** [comment]
看响应，日志在响应里。代理就是vpn会有代理地址。

**Comment by 21790EC** [comment]
我填了vpn的ip地址，顯示“地址解析失敗”，不知道是不是因為格式問題？
以下是響應裡的：

> (()=>{
    "use strict";
    const t = class {
        type;
        broadcastChannel = new BroadcastChannel("log://");
        constructor(t) {
            this.type = t
        }
        post(t, e) {
            this.broadcastChannel.postMessage({
                type: this.type,
                fn: t,
                data: JSON.stringify(e)
            })
        }
    }
      , e = (new t("bilibililive"),
    new t("ffmpeg"));
    let s;
    const o = [];
    let i, n = null;
    function a(t) {
        const e = t.split(/:/g);
        return 3600 * Number(e[0]) + 60 * Number(e[1]) + Number(e[2])
    }
    function c(t) {
        return "string" == typeof t ? ["-i", t] : t.map(((t,e)=>["-i", t])).flat()
    }
    function r(t) {
        s ??= globalThis.require("node:child_process");
        const {ffmpeg: r, playStreamPath: l, filePath: p, ua: d, protocolWhitelist: u, libx264: f, qid: h, ffmpegHeaders: g, concat: m} = t;
        let b = c(l).concat(m ? ["-c:v", "copy", "-c:a", "aac", p] : ["-c", "copy", p]);
        f && (b = c(l).concat(["-vcodec", "libx264", p])),
        g && b.unshift("-headers", g),
        d && b.unshift("-user_agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"),
        u && b.unshift("-protocol_whitelist", "file,http,https,tcp,tls"),
        b = ["-rw_timeout", "300000000", ...b],
        i = s.spawn(r, b),
        i.stdout.on("data", (function(t) {
            o.push(t.toString())
        }
        )),
        i.stderr.on("data", (function(t) {
            o.push(t.toString()),
            h && function(t, e) {
                if (/^\s*Input/i.test(e)) {
                    const t = e.match(/Duration:\s*\d+:\d+:\d+(\.\d+)?/gi);
                    if (t) {
                        const e = t[0].replace(/^Duration:\s*/i, "");
                        n = a(e)
                    }
                } else if (/time=\d+:\d+:\d+(\.\d+)?/i.test(e) && null !== n) {
                    const s = e.match(/time=\d+:\d+:\d+(\.\d+)?/gi);
                    if (s) {
                        const e = a(s[0].replace(/^time\s*=\s*/i, ""));
                        postMessage({
                            type: "progress",
                            data: Math.floor(e / n * 100),
                            qid: t
                        })
                    }
                }
            }(h, t.toString())
        }
        )),
        i.on("close", (function(...t) {
            e.post("util", {
                ffmpeg: r,
                input: l,
                output: p,
                cmd: b,
                stdout: o.join("\n")
            }),
            postMessage({
                type: "close",
                qid: h
            })
        }
        )),
        i.on("error", (function(t) {
            postMessage({
                type: "error",
                error: t
            })
        }
        ))
    }
    addEventListener("message", (function(t) {
        const {type: e} = t.data;
        switch (e) {
        case "start":
            r(t.data);
            break;
        case "stop":
            i.kill("SIGTERM")
        }
    }
    )),
    globalThis.requestIdleCallback?.((()=>s ??= globalThis.require("node:child_process")))
}
)();

**Comment by duan602728596** [comment]
响应里面的日志不是这个，是包含着命令、方法等的。你这个是错误信息吧。

**Comment by 21790EC** [comment]
那是這個嗎？
<img width="1638" alt="截圖 2023-08-30 下午11 56 37" src="https://github.com/duan602728596/48tools/assets/61772507/dd4b37c5-00ba-48b3-9afa-e10547ad741a">

下載時開發者工具跳出兩個請求，剛剛那個是第一個請求的響應，這個圖片裡的是第二個請求裡的

**Comment by duan602728596** [comment]
是这个，把下面的也截取了吧，下面的是ffmpeg的执行的log。

**Comment by 21790EC** [comment]
title: 执行ffmpeg命令
type: ffmpeg
function: util
   input: http://localhost:25110/proxy/bilibili-video?url=https%3A%2F%2Fupos-sz-mirroraliov.bilivideo.com%2Fupgcxcode%2F03%2F12%2F35421203%2F35421203_da3-1-30080.m4s%3Fe%3Dig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M%3D%26uipk%3D5%26nbs%3D1%26deadline%3D1693418116%26gen%3Dplayurlv2%26os%3Daliovbv%26oi%3D3699658041%26trid%3D20e29493354b411f97454949cd40b9b6u%26mid%3D551414264%26platform%3Dpc%26upsig%3D2bbeb2b0e7ef534a73500045a003e6a3%26uparams%3De%2Cuipk%2Cnbs%2Cdeadline%2Cgen%2Cos%2Coi%2Ctrid%2Cmid%2Cplatform%26bvc%3Dvod%26nettype%3D0%26orderid%3D0%2C1%26buvid%3D%26build%3D0%26f%3Du_0_0%26agrr%3D0%26bw%3D328398%26logo%3D80000000,http://localhost:25110/proxy/bilibili-video?url=https%3A%2F%2Fupos-sz-mirroraliov.bilivideo.com%2Fupgcxcode%2F03%2F12%2F35421203%2F35421203_da3-1-30080.m4s%3Fe%3Dig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M%3D%26uipk%3D5%26nbs%3D1%26deadline%3D1693418116%26gen%3Dplayurlv2%26os%3Daliovbv%26oi%3D3699658041%26trid%3D20e29493354b411f97454949cd40b9b6u%26mid%3D551414264%26platform%3Dpc%26upsig%3D2bbeb2b0e7ef534a73500045a003e6a3%26uparams%3De%2Cuipk%2Cnbs%2Cdeadline%2Cgen%2Cos%2Coi%2Ctrid%2Cmid%2Cplatform%26bvc%3Dvod%26nettype%3D0%26orderid%3D0%2C1%26buvid%3D%26build%3D0%26f%3Du_0_0%26agrr%3D0%26bw%3D328398%26logo%3D80000000
  output: /Users/e********n/Downloads/[B站下载]bv1GW411T7ga_3_精灵+粉红狙击手+上下左右+暴走少女+Mario,My Love_DASH.mp4
  ffmpeg: /usr/local/Cellar/ffmpeg
    args: -rw_timeout
          300000000
          -i
          http://localhost:25110/proxy/bilibili-video?url=https%3A%2F%2Fupos-sz-mirroraliov.bilivideo.com%2Fupgcxcode%2F03%2F12%2F35421203%2F35421203_da3-1-30080.m4s%3Fe%3Dig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M%3D%26uipk%3D5%26nbs%3D1%26deadline%3D1693418116%26gen%3Dplayurlv2%26os%3Daliovbv%26oi%3D3699658041%26trid%3D20e29493354b411f97454949cd40b9b6u%26mid%3D551414264%26platform%3Dpc%26upsig%3D2bbeb2b0e7ef534a73500045a003e6a3%26uparams%3De%2Cuipk%2Cnbs%2Cdeadline%2Cgen%2Cos%2Coi%2Ctrid%2Cmid%2Cplatform%26bvc%3Dvod%26nettype%3D0%26orderid%3D0%2C1%26buvid%3D%26build%3D0%26f%3Du_0_0%26agrr%3D0%26bw%3D328398%26logo%3D80000000
          -i
          http://localhost:25110/proxy/bilibili-video?url=https%3A%2F%2Fupos-sz-mirroraliov.bilivideo.com%2Fupgcxcode%2F03%2F12%2F35421203%2F35421203_da3-1-30080.m4s%3Fe%3Dig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M%3D%26uipk%3D5%26nbs%3D1%26deadline%3D1693418116%26gen%3Dplayurlv2%26os%3Daliovbv%26oi%3D3699658041%26trid%3D20e29493354b411f97454949cd40b9b6u%26mid%3D551414264%26platform%3Dpc%26upsig%3D2bbeb2b0e7ef534a73500045a003e6a3%26uparams%3De%2Cuipk%2Cnbs%2Cdeadline%2Cgen%2Cos%2Coi%2Ctrid%2Cmid%2Cplatform%26bvc%3Dvod%26nettype%3D0%26orderid%3D0%2C1%26buvid%3D%26build%3D0%26f%3Du_0_0%26agrr%3D0%26bw%3D328398%26logo%3D80000000
          -c:v
          copy
          -c:a
          aac
          /Users/e********n/Downloads/[B站下载]bv1GW411T7ga_3_精灵+粉红狙击手+上下左右+暴走少女+Mario,My Love_DASH.mp4

**Comment by 21790EC** [comment]
<img width="1792" alt="截圖 2023-08-31 上午12 16 53" src="https://github.com/duan602728596/48tools/assets/61772507/f0587e5f-0bd0-4ca8-b814-a320b42ce908">
這就是全部，後面截不到的已經複製給你了

我的天啊，但是前幾天都能成功下載的啊

**Comment by duan602728596** [comment]
<img width="494" alt="截屏2023-08-31 00 31 30" src="https://github.com/duan602728596/48tools/assets/17332657/facaba72-4ffa-4622-9175-cd4c4c5160d3">
找个vpn，试试这样配置代理吧，我怀疑是你那边的视频地址被ban了，被ban掉我就没办法了。

**Comment by 21790EC** [comment]
我試了
同樣是選擇分辨率後下載失敗
沒選還是360p

**Comment by 21790EC** [comment]
<img width="1154" alt="截圖 2023-08-31 上午8 12 17" src="https://github.com/duan602728596/48tools/assets/61772507/870e24c6-025d-4f5f-9148-d596ddd9aa2a">
這是使用vpn後的下載，和使用前沒有區別

這個情況是有vpn也沒救了嗎？

**Comment by duan602728596** [comment]
这个应该和地区有关，不是软件能解决的问题了。

**Comment by 21790EC** [comment]
好的 謝謝你
