### ISSUE TITLE
口袋48登录获取验证码失败-48加入了验证

### ISSUE THREAD

**Issue by lanfeng-shui** [duan602728596/48tools#88]
## 错误报告

口袋48登录获取验证码失败

## 复现步骤

请提供能够复现问题的步骤：
1. 口袋48登录
2. 验证码登录
3. 发送验证码
![image](https://github.com/duan602728596/48tools/assets/81756923/a7671489-8c08-4150-8704-f9356589c881)

 ## 预期行为

能够获取验证码并登录

## 使用环境

- 操作系统：Windows Pro 22H2 x64
- 软件版本：4.2.1

**Comment by duan602728596** [comment]
你这个是国外的区号吗？

**Comment by lanfeng-shui** [comment]
是的，我自己尝试在手机口袋app登陆，发现多了一个验证步骤，可能是这个原因 ![image](https://github.com/duan602728596/48tools/assets/81756923/0f6933d6-50be-4c6b-9361-71a14cf59230)> 你这个是国外的区号吗？

**Comment by duan602728596** [comment]
原来如此，可能是防止滥用的

**Comment by lanfeng-shui** [comment]
> 原来如此，可能是防止滥用的

那有办法能让国外的账号在48tools中正常登陆吗？

**Comment by duan602728596** [comment]
已经修复，等待发版

**Comment by lanfeng-shui** [comment]
> 已经修复，等待发版

辛苦啦
