### ISSUE TITLE
B站- 个人主页批量下载- 提示非法访问

### ISSUE THREAD

**Issue by lizh2023** [duan602728596/48tools#89]
## 错误报告

<img width="1000" alt="image" src="https://github.com/duan602728596/48tools/assets/134567388/1747593e-09eb-4db0-bba0-82ee99e89892">

## 复现步骤

如上图,
但是单个视频可以下载成功,
尝试过开启VPN与关闭VPN, 个人主页批量下载都一样提示“非法访问”

## 预期行为

之前使用48tool - 3.23.3版本, 个人主页批量下载跟单个下载都能顺利执行,
希望能修复这个问题

## 使用环境

- 操作系统： macOS Monterry 12.6.7
- 软件版本：48tool 4.3.0

**Comment by duan602728596** [comment]
账号登录了吗？

**Comment by lizh2023** [comment]
@duan602728596  修复好的版本, 需要重新下载安装新版吗?

**Comment by duan602728596** [comment]
> @duan602728596 修复好的版本, 需要重新下载安装吗?

还没有发版，需要等晚上回家才能发版。
