### ISSUE TITLE
直播类型新增了 游戏 的选项，后续会不会添加这个选项？

### ISSUE THREAD

**Issue by yunyeshanzhu** [duan602728596/48tools#91]
## 这个功能解决了什么问题？
可以筛选出我想要的

## 你期望的功能是怎样的？
直播类型新增了 游戏 的选项，后续会不会添加这个选项？

**Comment by duan602728596** [comment]
以前有直播和电台，现在多加了游戏是吧？

**Comment by yunyeshanzhu** [comment]
是的，之前是有视频、电台、录屏&nbsp; ，国庆期间袋王新加了游戏的活动


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "duan602728596/48tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月1日(星期天) 中午1:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [duan602728596/48tools] 直播类型新增了 游戏 的选项，后续会不会添加这个选项？ (Issue #91)





 
以前有直播和电台，现在多加了游戏是吧？
