### ISSUE TITLE
如何批量下载B站视频

### ISSUE THREAD

**Issue by GuoDer20** [duan602728596/48tools#97]
## 错误报告

<使用B站下载功能只能下载单个视频，无法批量下载，点击个人主页批量下载会弹出风险校验失败，尝试多次都是如此>

<img width="741" alt="屏幕截图 2023-12-10 005145" src="https://github.com/duan602728596/48tools/assets/118710979/6c6f2bad-cfb1-410b-af5b-b85599510cb8">

## 预期行为

<能够批量的下载B站视频>

## 使用环境

- 操作系统：win11
- 软件版本：4.5.2

**Comment by duan602728596** [comment]
接口现在需要登录才能请求到数据

**Comment by duan602728596** [comment]
已发版
