### ISSUE TITLE
公演录播下载不了

### ISSUE THREAD

**Issue by 8777655** [duan602728596/48tools#99]
## 错误报告
![2023-12-23](https://github.com/duan602728596/48tools/assets/154544525/f27b168c-5f1f-424c-a599-1542dcf44c1f)

## 使用环境

- 操作系统：
- 软件版本：

**Comment by 8777655** [comment]
加载不出来 最新版本 系统 Win11

**Comment by 8777655** [comment]
> ## 错误报告
![2023-12-22](https://github.com/duan602728596/48tools/assets/154544525/fb590461-4585-48ee-b95d-8a3ed7709d27)

> ## 复现步骤
> ## 预期行为
> ## 使用环境
> * 操作系统：Win11 64位
> * 软件版本：4.6.1

**Comment by duan602728596** [comment]
已修复
